import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";

// Register Service Worker (auto-generated by vite-plugin-pwa)
if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker.register("/sw.js", { scope: "/" }).catch(() => {
      // SW registration failed — app still works without it
    });
  });
}

// Track PWA install
window.addEventListener("appinstalled", () => {
  console.log("[PWA] H4CK3D Enterprise installed successfully");
});

createRoot(document.getElementById("root")!).render(<App />);
